In [3]:
!uv pip install -q numpy

In [4]:
import numpy as np

# Vectors in python and numpy

- np.array()
- np.arange()
- numpy.ndarray

In [6]:
# Python Vectors
x = [1,2,3]
y = [4,5,6]

z = [x[i]+y[i] for i in range(len(x))]
z

[5, 7, 9]

In [ ]:
# NumPy Arrays
x = np.array([1,2,3]) # numpy.ndarray
y = np.arange(4, 7) # [4,5,6]
z = x + y
z

array([5, 7, 9])

In [ ]:
# Operations
x = np.arange(1,4) # [1,2,3]
y = np.arange(4,7) # [4,5,6]
print(x+y)
print(x-y)
print(x*y)  # Hadamard Product
print(10*x) # Scaling Vector

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[10 20 30]


# List vs NumPy Arrays

In [13]:
x_lists = list(range(1, 1_000_001))
x_numpy = np.arange(1,1_000_001)

In [14]:
%timeit [2*i for i in x_lists]

115 ms ± 7.21 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [15]:
%timeit 2*x_numpy

2.31 ms ± 80.9 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# Complex Operations on Arrays

In [20]:
x = np.arange(1,5)
y = np.array([1, np.e, np.e**2, np.e**3])
print(x**2)
print(np.log10(x))
print(np.log(y))
print(x+5)
print(5*x + 2)

[ 1  4  9 16]
[0.         0.30103    0.47712125 0.60205999]
[0. 1. 2. 3.]
[6 7 8 9]
[ 7 12 17 22]


In [23]:
# Dot Product
np.dot(x, y), x@y, x.T @ y

(np.float64(108.9458796464607),
 np.float64(108.9458796464607),
 np.float64(108.9458796464607))

In [24]:
x

array([1, 2, 3, 4])

In [26]:
x.T # For 1-D array x and x.T are same

array([1, 2, 3, 4])

In [30]:
x == x.T

array([ True,  True,  True,  True])

# More Common

In [32]:
x = np.arange(1,5)
z = np.zeros(5)
o = np.ones(5)

print(x,z,o)

[1 2 3 4] [0. 0. 0. 0. 0.] [1. 1. 1. 1. 1.]


In [34]:
# Norm Of Vectors
np.linalg.norm(x) # l2 norm

np.float64(5.477225575051661)

In [35]:
np.linalg.norm(x, ord=1) # l2 norm

np.float64(10.0)

In [36]:
# Shape vs Dim
# Shape = no. of components
x = np.array([1,2,3,4])
x.shape

(4,)

In [ ]:
x.ndim # rows

1